### ISSUE TITLE
No content message still render as a valid message

### ISSUE THREAD

**Issue by nnh53** [bentran-vn/PERSONAL-F_STRANGER-ANONYMOUS_CHATTING_PLATFORM#1]
Message has no content still able to be click send or enter 

![image](https://github.com/bentran-vn/PERSONAL-F_STRANGER-ANONYMOUS_CHATTING_PLATFORM/assets/113448161/ec7ea214-a936-4171-b694-9734c9f86e34)

**Comment by bentran1vn** [comment]
Thank you for finding an error. Your contribution is a piece to make our product more complete !
